repos:
# - repo: https://github.com/kynan/nbstripout
#   rev: 0.8.1
#   hooks:
#     - id: nbstripout
#       files: ".ipynb"
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
    - id: black
      args: ["--line-length", "200"]
      language_version: python3.9
- repo: https://github.com/srstevenson/nb-clean
  rev: 4.0.1
  hooks:
    - id: nb-clean
      args:
        - --remove-empty-cells
